services:
  medical_device_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MEDICAL_DEVICE_SERVICE_HOST=medical_device_service
      - MEDICAL_DEVICE_SERVICE_PORT=5000
      - REACT_APP_GATEWAT_WBEBSOCKT_HOST=medical_device_gateway
      - REACT_APP_GATEWAT_WBEBSOCKT_PORT=8765
    command: npm run start
    networks:
      - medical_device

networks:
  medical_device:
    name: medical_device
