name: medical_device_web 项目文件对应 CI/CD 工作流

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PASSWORD: wY74108520
      SERVER_IP: 110.41.165.162
      SERVER_PORT: 2022
      PROJECT_PATH: /root/medical_device/medical_device_web
      NGINX_CONF_PATH: /etc/nginx/nginx.conf

    steps:
      - name: 检查代码库
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.6'

      - name: 安装所需依赖
        run: npm ci

      - name: 搭建项目
        run: npm run build

      - name: 安装 rsync,sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: 测试SSH连接
        run: |
          echo "Testing SSH connection to ${{ env.SERVER_IP }} on port ${{ env.SERVER_PORT }}"
          sshpass -p "${{ env.SSH_PASSWORD }}" ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ env.SERVER_PORT }} root@${{ env.SERVER_IP }} "echo 'Connection successful'"

      - name: 使用rsync同步文件到服务器
        run: |
          sshpass -p "${{ env.SSH_PASSWORD }}" rsync -avz -e "ssh -p ${{ env.SERVER_PORT }} -o StrictHostKeyChecking=no" ./ root@${{ env.SERVER_IP }}:${{ env.PROJECT_PATH }}

      - name: 确保目标目录存在并具有适当权限
        run: |
          sshpass -p "${{ env.SSH_PASSWORD }}" ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ env.SERVER_PORT }} root@${{ env.SERVER_IP }} "mkdir -p ${{ env.PROJECT_PATH }} && chmod 700 ${{ env.PROJECT_PATH }}"

      - name: 更新 Nginx 配置
        run: |
          sshpass -p "${{ env.SSH_PASSWORD }}" ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ env.SERVER_PORT }} ${SSH_USERNAME}@${{ env.SERVER_IP }} "sed -i 's#/var/www/html#${{ env.PROJECT_PATH }}#' ${{ env.NGINX_CONF_PATH }} && service nginx reload"